/**
 * Fills backend/.env.production from a Render Postgres connection string, so
 * you can paste one URL instead of hand-splitting it into five variables
 * (and getting the host suffix wrong, which is exactly what happened to the
 * previous attempt: a bare `dpg-...` id that can never resolve).
 *
 *   node scripts/configure-online.mjs "postgresql://user:pass@host:5432/db"
 *   node scripts/configure-online.mjs --from-env DATABASE_URL
 *
 * Use the INTERNAL Database URL from the Render dashboard. The internal one
 * resolves on Render's private network only; the external one is reachable from
 * anywhere but burns bandwidth on every request.
 *
 * Existing PayChangu keys in the file are preserved. The password is never
 * echoed.
 */

import fs from 'fs';
import path from 'path';

const root = path.resolve(import.meta.dirname, '..');
const target = path.join(root, '.env.production');

const args = process.argv.slice(2);

function readArg() {
    if (args.includes('--from-env')) {
        const name = args[args.indexOf('--from-env') + 1] || 'DATABASE_URL';
        const value = process.env[name];
        if (!value) throw new Error(`--from-env given but ${name} is not set`);
        return value;
    }
    const url = args.find((a) => !a.startsWith('--'));
    if (!url) {
        throw new Error(
            'no connection string given.\n' +
                '  node scripts/configure-online.mjs "postgresql://user:pass@host:5432/db"\n' +
                '  node scripts/configure-online.mjs --from-env DATABASE_URL'
        );
    }
    return url;
}

/** Splits a postgres:// URL into the pieces the pg Pool wants. */
function parse(url) {
    const parsed = new URL(url);

    const scheme = parsed.protocol.replace(':', '');
    if (scheme !== 'postgres' && scheme !== 'postgresql') {
        throw new Error(`expected a postgres:// URL, got "${scheme}://"`);
    }

    const database = parsed.pathname.replace(/^\//, '');
    if (!database) throw new Error('no database name in the URL path');

    const password = decodeURIComponent(parsed.password);
    if (!password) throw new Error('no password in the URL');

    return {
        host: parsed.hostname,
        port: parsed.port || '5432',
        user: decodeURIComponent(parsed.username),
        password,
        database,
    };
}

const cfg = parse(readArg());

// Render Postgres hosts come in two shapes, and using the wrong one fails in
// confusing ways:
//   internal -> "dpg-davuu7m0tbcc73fgo1cg-a"                  (no dots at all)
//   external -> "dpg-davuu7m0tbcc73fgo1cg-a.oregon-postgres.render.com"
// Internal resolves only inside Render's network, so a service uses it and your
// laptop cannot. External resolves everywhere, so your laptop can and Render
// services generally should not (it bills bandwidth for every request).
const isInternal = !cfg.host.includes('.');
const looksLikeRender = /^dpg-[a-z0-9]+-a$/i.test(cfg.host) || /\.render\.com$/i.test(cfg.host);

if (looksLikeRender && isInternal) {
    console.log('  host looks INTERNAL (Render private network)');
    console.log('  -> a Render service can use this; your machine cannot.');
} else if (looksLikeRender) {
    console.log('  host looks EXTERNAL (reachable from anywhere)');
    console.log('  -> fine for local dev:online; Render services should use the INTERNAL url.');
} else {
    console.warn(`  WARNING: "${cfg.host}" is not shaped like a Render Postgres host.`);
    console.warn('           If this is meant to be Render, check you copied the whole host.');
}

const network = isInternal ? 'INTERNAL' : 'EXTERNAL';

// Carry over anything already in the file that this script does not own, so
// re-running it does not wipe the PayChangu keys.
const previous = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
const keep = (key) => {
    const hit = previous.match(new RegExp(`^${key}=(.*)$`, 'm'));
    return hit ? hit[1].trim() : '';
};

const paychanguSecret = keep('PAYCHANGU_SECRET_KEY');
const webhookSecret = keep('WEBHOOK_SECRET');
const paychanguBase = keep('PAYCHANGU_BASE_URL') || 'https://api.paychangu.com';

const body = `# ONLINE / Render target. Git-ignored — see .env.production.example.
#
# Generated by scripts/configure-online.mjs from the ${network} Database URL.
#
${
    isInternal
        ? `# Render's INTERNAL host only resolves inside Render's network, so this
# file is a faithful mirror of what the deployed service sees but CANNOT be
# reached from your machine. For local dev:online, regenerate it with the
# external URL instead.`
        : `# This is the EXTERNAL host, so it works from your machine for
# dev:online. The deployed service is given the INTERNAL url instead, so the
# two differ by design - do not assume they are interchangeable.`
}
SERVER_MODE=online
NODE_ENV=production

DB_HOST=${cfg.host}
DB_PORT=${cfg.port}
DB_USER=${cfg.user}
DB_PASSWORD=${cfg.password}
DB_NAME=${cfg.database}

# Render's Postgres refuses plaintext connections.
DB_SSL=true
DB_CONNECT_ATTEMPTS=10

# PayChangu TEST keys. Swap for live keys once the app is fully tested.
PAYCHANGU_SECRET_KEY=${paychanguSecret || 'SEC-TEST-your-key-here'}
PAYCHANGU_BASE_URL=${paychanguBase}
WEBHOOK_SECRET=${webhookSecret || 'wh_sec_test_your-webhook-secret'}
`;

fs.writeFileSync(target, body, 'utf8');

console.log('\nWrote backend/.env.production');
console.log(`  DB_HOST   ${cfg.host}`);
console.log(`  DB_PORT   ${cfg.port}`);
console.log(`  DB_USER   ${cfg.user}`);
console.log(`  DB_NAME   ${cfg.database}`);
console.log(`  DB_SSL    true`);
console.log(`  password ${'*'.repeat(cfg.password.length)} (${cfg.password.length} chars, not shown)`);
if (!paychanguSecret || !webhookSecret) {
    console.log('\n  Still empty: PAYCHANGU_SECRET_KEY / WEBHOOK_SECRET');
    console.log('  Copy them from backend/.env, or set them on the Render service.');
}
