/**
 * Fills backend/.env.production from a Render Postgres connection string, so
 * you can paste one URL instead of hand-splitting it into five variables
 * (and getting the host suffix wrong, which is exactly what happened to the
 * previous attempt: a bare `dpg-...` id that can never resolve).
 *
 *   node scripts/configure-online.mjs "postgresql://user:pass@host:5432/db"
 *   node scripts/configure-online.mjs --from-env DATABASE_URL
 *
 * Use the INTERNAL Database URL from the Render dashboard. The internal one
 * resolves on Render's private network only; the external one is reachable from
 * anywhere but burns bandwidth on every request.
 *
 * Existing PayChangu keys in the file are preserved. The password is never
 * echoed.
 */

import fs from 'fs';
import path from 'path';

const root = path.resolve(import.meta.dirname, '..');
const target = path.join(root, '.env.production');

const args = process.argv.slice(2);

function readArg() {
    if (args.includes('--from-env')) {
        const name = args[args.indexOf('--from-env') + 1] || 'DATABASE_URL';
        const value = process.env[name];
        if (!value) throw new Error(`--from-env given but ${name} is not set`);
        return value;
    }
    const url = args.find((a) => !a.startsWith('--'));
    if (!url) {
        throw new Error(
            'no connection string given.\n' +
                '  node scripts/configure-online.mjs "postgresql://user:pass@host:5432/db"\n' +
                '  node scripts/configure-online.mjs --from-env DATABASE_URL'
        );
    }
    return url;
}

/** Splits a postgres:// URL into the pieces the pg Pool wants. */
function parse(url) {
    const parsed = new URL(url);

    const scheme = parsed.protocol.replace(':', '');
    if (scheme !== 'postgres' && scheme !== 'postgresql') {
        throw new Error(`expected a postgres:// URL, got "${scheme}://"`);
    }

    const database = parsed.pathname.replace(/^\//, '');
    if (!database) throw new Error('no database name in the URL path');

    const password = decodeURIComponent(parsed.password);
    if (!password) throw new Error('no password in the URL');

    return {
        host: parsed.hostname,
        port: parsed.port || '5432',
        user: decodeURIComponent(parsed.username),
        password,
        database,
    };
}

const cfg = parse(readArg());

// The most likely mistake with these URLs is grabbing the external one, or
// pasting the id without the domain. Both fail in confusing ways, so say so
// now rather than at connection time.
if (/\.oregon-postgres\.render\.com$/.test(cfg.host)) {
    console.log('  host looks like a Render Postgres host');
} else {
    console.warn(`  WARNING: "${cfg.host}" does not end in .oregon-postgres.render.com`);
    console.warn('           If this is meant to be Render, check you copied the whole host.');
}

if (/-\d{4}\.oregon-postgres\.render\.com$/.test(cfg.host)) {
    console.warn('  WARNING: that host looks EXTERNAL. On Render you want the INTERNAL');
    console.warn('           Database URL — the external one cannot be reached from inside');
    console.warn('           Render\'s network, and the internal one cannot be reached from');
    console.warn('           your machine.');
}

// Carry over anything already in the file that this script does not own, so
// re-running it does not wipe the PayChangu keys.
const previous = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
const keep = (key) => {
    const hit = previous.match(new RegExp(`^${key}=(.*)$`, 'm'));
    return hit ? hit[1].trim() : '';
};

const paychanguSecret = keep('PAYCHANGU_SECRET_KEY');
const webhookSecret = keep('WEBHOOK_SECRET');
const paychanguBase = keep('PAYCHANGU_BASE_URL') || 'https://api.paychangu.com';

const body = `# ONLINE / Render target. Git-ignored — see .env.production.example.
#
# Generated by scripts/configure-online.mjs. The host below came from Render's
# INTERNAL Database URL, which only resolves inside Render's network. That
# means "npm run dev:online" will NOT reach this database from your machine —
# it works from the service's Shell tab, and from your laptop only if you swap
# in the external URL.
SERVER_MODE=online
NODE_ENV=production

DB_HOST=${cfg.host}
DB_PORT=${cfg.port}
DB_USER=${cfg.user}
DB_PASSWORD=${cfg.password}
DB_NAME=${cfg.database}

# Render's Postgres refuses plaintext connections.
DB_SSL=true
DB_CONNECT_ATTEMPTS=10

# PayChangu TEST keys. Swap for live keys once the app is fully tested.
PAYCHANGU_SECRET_KEY=${paychanguSecret || 'SEC-TEST-your-key-here'}
PAYCHANGU_BASE_URL=${paychanguBase}
WEBHOOK_SECRET=${webhookSecret || 'wh_sec_test_your-webhook-secret'}
`;

fs.writeFileSync(target, body, 'utf8');

console.log('\nWrote backend/.env.production');
console.log(`  DB_HOST   ${cfg.host}`);
console.log(`  DB_PORT   ${cfg.port}`);
console.log(`  DB_USER   ${cfg.user}`);
console.log(`  DB_NAME   ${cfg.database}`);
console.log(`  DB_SSL    true`);
console.log(`  password ${'*'.repeat(cfg.password.length)} (${cfg.password.length} chars, not shown)`);
if (!paychanguSecret || !webhookSecret) {
    console.log('\n  Still empty: PAYCHANGU_SECRET_KEY / WEBHOOK_SECRET');
    console.log('  Copy them from backend/.env, or set them on the Render service.');
}
